### ISSUE TITLE
`extract_array_2d` can give results of different size.

### ISSUE THREAD

**Issue by hamogu** [astropy/imageutils#21]
```
>>> large_array = np.arange(30).reshape(5,6)
>>> extract_array_2d(large_array, (3, 4), (7, 7))
 array([[65, 66, 67, 68, 69],
       [75, 76, 77, 78, 79],
       [85, 86, 87, 88, 89]])
>>> extract_array_2d(large_array, (3, 4), (0, 0))
array([[0, 1, 2],
       [6, 7, 8]])
```
It would be useful for me if we had either:
- an option to return where the position I put in falls on the new image (`(1,2)` in the first example and `(0,0)` in the second example) or
- an option to always return a ` (3,4)` array, but fill missing values in some way (e.g. nan or return a mask of invalid entires) or
- both (via a keyword).
What do peopele think?

**Comment by astrofrog** [comment]
@hamogu - can you check that this is still happening in the function that has been merged into astropy?

http://docs.astropy.org/en/latest/api/astropy.nddata.utils.extract_array.html#astropy.nddata.utils.extract_array

**Comment by hamogu** [comment]
Yes, it does. I'll open it as an astropy issue and also provide a working example (I must have edited the example above and broke it in the process).

**Comment by astrofrog** [comment]
Looks like this was fixed in https://github.com/astropy/astropy/pull/3727 - @hamogu, feel free to re-open an issue on the astropy repository if not.

**Comment by hamogu** [comment]
Yes, it's fixed there.
