### ISSUE TITLE
Add crop = cutout function

### ISSUE THREAD

**Issue by cdeil** [astropy/imageutils#4]
One of the basic image processing functions is `crop`, a.k.a. `cutout`.

API proposal:
```python
def crop(data, wcs, bounding_box):
    data_new = # a view, not a copy
    wcs_new = # copy and modify the input wcs
    return data_new, wcs_new
```

Existing implementations (please add links if there is other code that might be useful):
* https://gammapy.readthedocs.org/en/latest/api/gammapy.image.crop_image.html

To be discussed:
* How should the `bounding_box` be specified? (In Gammapy I've started to implement a class for this)

**Comment by keflavich** [comment]
Over the past few days, I've had a need for this functionality on 3 separate occasions.  So, big :+1:.

**Comment by cdeil** [comment]
@larrybradley has implemented this in https://github.com/astropy/astropy/pull/3823 .
Closing this issue so that discussion can continue there ...
